-- Esquema inicial · PostgreSQL (Netlify DB / Neon)
-- Mismas tablas y columnas que la versión SQLite. Instantes en milisegundos (BIGINT).

CREATE TABLE empresa (
  id           INTEGER PRIMARY KEY CHECK (id = 1),
  nombre       TEXT    NOT NULL,
  rubro        TEXT    NOT NULL DEFAULT 'Moda y accesorios',
  zona_horaria TEXT    NOT NULL DEFAULT 'America/Lima',
  moneda       TEXT    NOT NULL DEFAULT 'PEN',
  config       TEXT    NOT NULL DEFAULT '{}',
  actualizado  BIGINT  NOT NULL
);

CREATE TABLE tiendas (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo    TEXT    NOT NULL UNIQUE,
  nombre    TEXT    NOT NULL,
  direccion TEXT    NOT NULL DEFAULT '',
  lat       DOUBLE PRECISION NOT NULL,
  lng       DOUBLE PRECISION NOT NULL,
  radio_m   INTEGER NOT NULL DEFAULT 80,
  activa    INTEGER NOT NULL DEFAULT 1,
  creado    BIGINT  NOT NULL
);

CREATE TABLE usuarios (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo          TEXT    NOT NULL UNIQUE,
  nombre          TEXT    NOT NULL,
  telefono        TEXT    NOT NULL DEFAULT '',
  rol             TEXT    NOT NULL CHECK (rol IN ('admin', 'supervisor', 'colaborador')),
  secreto         TEXT    NOT NULL,
  tienda_id       BIGINT REFERENCES tiendas(id) ON DELETE SET NULL,
  activo          INTEGER NOT NULL DEFAULT 1,
  dispositivo     TEXT,
  intentos        INTEGER NOT NULL DEFAULT 0,
  bloqueado_hasta BIGINT,
  debe_cambiar    INTEGER NOT NULL DEFAULT 0,
  creado          BIGINT  NOT NULL
);

CREATE TABLE sesiones (
  token_hash TEXT    PRIMARY KEY,
  usuario_id BIGINT  NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  creado     BIGINT  NOT NULL,
  expira     BIGINT  NOT NULL,
  visto      BIGINT  NOT NULL,
  agente     TEXT,
  ip         TEXT
);
CREATE INDEX sesiones_usuario ON sesiones(usuario_id);
CREATE INDEX sesiones_expira ON sesiones(expira);

CREATE TABLE plantillas (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT  NOT NULL REFERENCES tiendas(id) ON DELETE CASCADE,
  dia       INTEGER NOT NULL CHECK (dia BETWEEN 0 AND 6),
  inicio    TEXT    NOT NULL,
  fin       TEXT    NOT NULL,
  cupos     INTEGER NOT NULL DEFAULT 1 CHECK (cupos BETWEEN 1 AND 10)
);
CREATE INDEX plantillas_tienda ON plantillas(tienda_id, dia);

CREATE TABLE dias_especiales (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id BIGINT REFERENCES tiendas(id) ON DELETE CASCADE,
  fecha     TEXT    NOT NULL,
  cerrado   INTEGER NOT NULL DEFAULT 0,
  turnos    TEXT    NOT NULL DEFAULT '[]',
  motivo    TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX dias_especiales_fecha ON dias_especiales(fecha);

CREATE TABLE dias_generados (
  tienda_id BIGINT NOT NULL REFERENCES tiendas(id) ON DELETE CASCADE,
  fecha     TEXT   NOT NULL,
  PRIMARY KEY (tienda_id, fecha)
);

CREATE TABLE turnos (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tienda_id    BIGINT  NOT NULL REFERENCES tiendas(id) ON DELETE CASCADE,
  fecha        TEXT    NOT NULL,
  inicio       TEXT    NOT NULL,
  fin          TEXT    NOT NULL,
  puesto       INTEGER NOT NULL DEFAULT 1,
  usuario_id   BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  origen       TEXT    NOT NULL DEFAULT 'plantilla' CHECK (origen IN ('plantilla', 'especial', 'manual')),
  asignado_por TEXT,
  asignado_en  BIGINT,
  ejemplo      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX turnos_fecha ON turnos(fecha, tienda_id);
CREATE INDEX turnos_usuario ON turnos(usuario_id, fecha);

CREATE TABLE marcas (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id    BIGINT  NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  turno_id      BIGINT REFERENCES turnos(id) ON DELETE SET NULL,
  tienda_id     BIGINT REFERENCES tiendas(id) ON DELETE SET NULL,
  tipo          TEXT    NOT NULL CHECK (tipo IN ('entrada', 'control', 'salida')),
  fecha         TEXT    NOT NULL,
  hora          TEXT    NOT NULL,
  ts            BIGINT  NOT NULL,
  capturado     BIGINT,
  lat           DOUBLE PRECISION,
  lng           DOUBLE PRECISION,
  precision_m   DOUBLE PRECISION,
  distancia_m   DOUBLE PRECISION,
  estado        TEXT    NOT NULL CHECK (estado IN ('dentro', 'fuera', 'imprecisa', 'sin_gps')),
  observaciones TEXT    NOT NULL DEFAULT '[]',
  dispositivo   TEXT,
  simulado      INTEGER NOT NULL DEFAULT 0,
  ejemplo       INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX marcas_turno ON marcas(turno_id, usuario_id);
CREATE INDEX marcas_usuario_fecha ON marcas(usuario_id, fecha);
CREATE INDEX marcas_fecha ON marcas(fecha);

CREATE TABLE reportes_turno (
  turno_id    BIGINT NOT NULL REFERENCES turnos(id) ON DELETE CASCADE,
  usuario_id  BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  apertura    TEXT   NOT NULL DEFAULT '[]',
  cierre      TEXT   NOT NULL DEFAULT '[]',
  ventas      INTEGER,
  prendas     INTEGER,
  efectivo    DOUBLE PRECISION,
  digital     DOUBLE PRECISION,
  tarjeta     DOUBLE PRECISION,
  nota        TEXT   NOT NULL DEFAULT '',
  actualizado BIGINT NOT NULL,
  PRIMARY KEY (turno_id, usuario_id)
);

CREATE TABLE multas (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id     BIGINT  NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  turno_id       BIGINT REFERENCES turnos(id) ON DELETE SET NULL,
  fecha          TEXT    NOT NULL,
  tipo           TEXT    NOT NULL CHECK (tipo IN ('tardanza', 'falta', 'salida_anticipada', 'manual')),
  monto          DOUBLE PRECISION NOT NULL,
  detalle        TEXT    NOT NULL,
  estado         TEXT    NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'pagada', 'anulada')),
  creada         BIGINT  NOT NULL,
  notificada     BIGINT,
  vista          BIGINT,
  pagada         BIGINT,
  motivo_anulada TEXT,
  ejemplo        INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX multas_unicas ON multas(turno_id, usuario_id, tipo) WHERE turno_id IS NOT NULL;
CREATE INDEX multas_usuario ON multas(usuario_id, estado);
CREATE INDEX multas_fecha ON multas(fecha);

CREATE TABLE justificaciones (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id   BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  multa_id     BIGINT REFERENCES multas(id) ON DELETE CASCADE,
  turno_id     BIGINT REFERENCES turnos(id) ON DELETE SET NULL,
  motivo       TEXT   NOT NULL,
  estado       TEXT   NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
  respuesta    TEXT,
  creada       BIGINT NOT NULL,
  resuelta     BIGINT,
  resuelta_por BIGINT REFERENCES usuarios(id) ON DELETE SET NULL
);
CREATE INDEX justificaciones_multa ON justificaciones(multa_id);

CREATE TABLE coberturas (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  turno_id       BIGINT NOT NULL REFERENCES turnos(id) ON DELETE CASCADE,
  solicitante_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  motivo         TEXT   NOT NULL DEFAULT '',
  estado         TEXT   NOT NULL DEFAULT 'abierta' CHECK (estado IN ('abierta', 'tomada', 'cancelada', 'vencida')),
  tomada_por     BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  creada         BIGINT NOT NULL,
  resuelta       BIGINT
);
CREATE INDEX coberturas_estado ON coberturas(estado);

CREATE TABLE avisos (
  clave TEXT   PRIMARY KEY,
  tipo  TEXT   NOT NULL,
  en    BIGINT NOT NULL,
  por   BIGINT REFERENCES usuarios(id) ON DELETE SET NULL
);

CREATE TABLE auditoria (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts         BIGINT NOT NULL,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  accion     TEXT   NOT NULL,
  entidad    TEXT,
  entidad_id TEXT,
  detalle    TEXT,
  ip         TEXT
);
CREATE INDEX auditoria_ts ON auditoria(ts);
